# Generated by Django 3.1.4 on 2021-03-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='participation',
            field=models.DecimalField(decimal_places=6, max_digits=20, null=True),
        ),
    ]
