# Generated by Django 3.1.4 on 2021-03-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210311_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='participation',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
